#!/usr/bin/env python3
### Lottery Picker #############
# Version 0.1 by Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################
import random

def randint(low, high):
    return int(round(low + random.SystemRandom().random() * (high - low)))

numbers = []
for n in range(0, 5):
    while True:
        x = randint(1, 56)
        if x not in numbers:
            numbers.append(x)
            break
print('  Numbers: {}'.format(numbers))
print('Powerball: {}'.format(randint(1, 46)))
