#!/bin/bash
#
# Modified version for ncmpcpp. Based on:
#
### MPD Ratings ################
# Version 0.1 by Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################
# Dependencies:
# - mpc
#

# Be sure to change these to reflect your setup.
library="$HOME/Music/Library"
playlists="$HOME/Music/Playlists"
lock="/tmp/mpd-ratings.lock"

song=$(mpc current -f "%file%")
pl_prefix='rated-'
pl_suffix='.m3u'

if [[ -z "$song" ]]; then
    echo 'No song is playing.'
    exit 1
elif [[ "$1" -lt 0 || "$1" -gt 5 ]]; then
    echo "Rating must be between 1 and 5. Or zero to delete the current song's rating."
    exit 1
fi

# Allow only one instance by creating a lock file.
if [[ -f "$lock" ]]; then
    echo "Rating failed! Another instance is running."
    exit 1
fi

# Lock.
touch "$lock"

# Remove the song from other rating playlists if found.
for n in {1..5}; do
    f="$playlists/${pl_prefix}$n${pl_suffix}"
    tmp="$playlists/tmp.m3u"
    if [[ -f "$f" ]]; then
        grep -vF "$song" "$f" > "$tmp"
        mv "$tmp" "$f"
    fi
done

# Append the song to the new rating playlist.
if [[ $1 -ne 0 ]]; then
    f="$playlists/${pl_prefix}$1${pl_suffix}"
    mkdir -p "$playlists"
    echo "$song" >> "$f"
    sort -u "$f" -o "$f"
fi

[[ -f "/tmp/new.m3u" ]] && rm "/tmp/new.m3u"

# Unlock.
rm "$lock"
