#!/bin/bash
. mpc-common
[[ -z "${song}" ]] && exit 1
[[ $song =~ '.zip/' ]] && song=${song%/*}
mpc del 0
mkdir -p "${trash}"
mv "${library}/${song}" "${trash}"
mpc update
song=${song##*/} song=${song%.*}
[[ ${#song} -gt 40 ]] && song="${song:0:40}..."
notice "$song\nmoved to trash."
