#!/bin/bash
. mpc-common
if [[ "${1}" != '--scrobble' ]]; then
    killall mpdscribble &> /dev/null
else
    shift
    pidof mpdscribble || mpdscribble &> /dev/null
fi
[[ -z "${2}" ]] && syntax "field query"
mpc -q stop
mpc -q clear
mpc search $* | mpc add
mpc play
