#!/bin/bash
. mpc-common
[[ -z "${song}" ]] && exit 1
[[ -z "${1}" ]] && syntax 'playlist'
for playlist in "${@}"; do
    echo "${library}/${song}" >> "${playlists}/${playlist}.m3u"
    sort -u "${playlists}/${playlist}.m3u" -o "${playlists}/${playlist}.m3u"
done
song=${song##*/}
[[ ${#song} -gt 20 ]] && song="${song:0:20}..."
notice "${song}\nadded to\n$(for playlist in "${@}"; do
    [[ ${#playlist} -gt 20 ]] && playlist="${playlist:0:20}..."
    echo "'${playlist}'"
done)"
