#!/bin/bash
set -f
network=($(iwconfig 2> /dev/null | grep -o '"\(.*\)"'))
quality=($(iwconfig 2> /dev/null | grep -o '[0-9]\+/[0-9]\+'))
colors=(EAA EEA AEA 9F9 6F6)
if [[ "${network}" ]]; then
    for ((n=0; n<${#network[@]}; n++)); do
        echo -n "<fc=#${colors[$((${quality[n]/\//*4/}))]}>${network[n]}</fc>"
    done
else
    echo '<fc=red>offline</fc>'
fi
