#!/bin/bash
shopt -s nocasematch
mh='iandrio'
f=$(mpc current -f '%file%')
if [[ -z $f ]]; then
    ms=$(ping $mh -qc1 | head -1 | cut -d' ' -f3 | tr -d '()')
    if [[ $ms == '192.168.1.3' && $mh != $HOSTNAME ]]; then
        echo -n "$HOSTNAME isn't playing anything, but $mh's "
        ssh iandrio $0
        exit
    else
        echo 'MPD is not playing anything.'
        exit
    fi
fi
[[ $f =~ '.zip/' ]] && f=${f%/*}
t=${f##*.}
mpc current -f 'MPD is playing "[%title%|%file%]"[ by %artist%] -' | tr '\n' ' '
case "$t" in
    mp?|og?|flac|wma)
        echo -n "$t" | tr '[a-z]' '[A-Z]'
        echo ' audio'
        ;;
    *)
        file -bz "$HOME/Music/Library/$f" |
            sed 's/ sound data//; s/Title:/titled/;
                 s/ (Zip .*//; s/ *\\032.*\\001//'
        ;;
esac
