#!/bin/bash
### Initramfs Extractor #########
# Version 0.1 by Scott Garrett  #
# Wintervenom[(at)]archlinux.us #
#################################
#
# Based on Extract-Kernel-Initramfs by Mistadman:
# https://github.com/mistadman/Extract-Kernel-Initramfs
#
### Dependencies ###
#
# - Bash 4 or later
# - lzma (XZ Utils)
# - bzip2
# - gzip
#

tmp='/tmp'
dd='dd status=noxfer'

cleanup () {
    echo 'Cleaning up...'
    [[ $bn ]] &&
        rm "$tmp/$bn".* &> /dev/null
}

fatal () {
    echo "$1"
    cleanup
    exit 1
}

bgrep () {
    grep -Paobm1 "$@" | head -1 | cut -d: -f1
}

extract () {
    echo "Looking for start of $1... "
    local ext sig cmd o
    for ext in gz lzma bz2 cpio; do
        case "$ext" in
            gz)
                sig='\x1F\x8B\x08\x00'
                cmd='gunzip -q'
                ;;
            lzma)
                sig='\x{5D}\x{00}\x..\x{FF}\x{FF}\x{FF}\x{FF}\x{FF}\x{FF}'
                cmd='unlzma -qq'
                ;;
            bz2)
                sig='\x{31}\x{41}\x{59}\x{26}\x{53}\x{59}'
                cmd='bunzip2 -q'
                ;;
            *)
                sig='070701'
                cmd='cat'
                ;;
        esac
        echo -n "  ...with $ext header... "
        o=$(bgrep "$sig" "$2")
        if [[ $o ]]; then
            echo -n "found at byte $o"
            [[ $e == 'bz2' ]] &&
                echo " ($((o -= 4)))"
            echo '.'
            break
        else
            echo "not found."

        fi
    done
    [[ -z $o ]] &&
        fatal "No $1 found."
    echo "Extracting and decompressing $1..."
    $dd if="$2" bs=1 skip=$o | $cmd > "$3"
}

bn=${1##*/}
f="$tmp/$bn"
extract 'kernel image' "$1" "$f.img"
extract 'cpio archive' "$f.img" "$f.cpio"
rm "$f.img"
f+='.cpio'

echo -n 'Looking for start of initramfs... '
a=$(bgrep '070701' "$f")
[[ -z $a ]] &&
    fatal 'not found.'
echo "found at byte $a."

echo -n 'Looking for end of initramfs... '
b=$(bgrep 'TRAILER!!!' "$f")
[[ -z $b ]] &&
    fatal 'not found.'
echo "found at byte $b ($((b += 14)))."

((c = b - a))
echo -n "Size: $c bytes"
((c < 0)) &&
    fatal " - mismatch."
echo

echo 'Extracting initramfs...'
dd if="$f" bs=1 skip=$a count=$c of="$bn.cpio"
rm "$f"
mkdir -p "$bn.cpio.d"
cd "$bn.cpio.d"
cpio -id --no-absolute-filename < "../$bn.cpio"
cleanup
