#!/bin/bash
### WM Session Manager #########
# Version 0.2 by Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################
wms=(herbstluftwm i3 dwm-session openbox-session)
actions=('[Quit]' '[Hibernate]' '[Suspend]' '[Reboot]' '[Shutdown]' '[Save]')
reset=(xmobar i3bar trayer dzen2 tint2 barstatus xbindkeys syndaemon)

basename=$0
basename=${basename##*/}
pidfile="/tmp/.$USER-$basename.pid"
wmfile="/tmp/.$USER-$basename.wm"
savefile="$HOME/.$basename"

[[ -f "$pidfile" ]] && wsmpid=$(cat "$pidfile")


onkill_herbstluftwm () {
    herbstclient quit
}

silentkill () {
    for p in "$@"; do
        if type -t "onkill_$p"; then
            "onkill_$p"
        else
            killall $p &> /dev/null
        fi
    done
}


if [[ "$1" == 'menu' ]]; then
    if [[ -z "$wsmpid" ]]; then
        echo 'No instance of WM Session Manager seems to be running.'
        exit 1
    fi
    selection=$(printf "%s\n" "${actions[@]}" "${wms[@]}" |
        dmenu -p 'X Session:' -i $DMENU_OPTIONS)
    [[ -z "$selection" ]] && exit
    [[ -f "$wmfile" ]] && wm=$(cat "$wmfile")
    case "$selection" in
        "${actions[0]}")
            if [[ "$wm" ]]; then
                mv "$wmfile" "$savefile"
                silentkill -w "$wm"
                sleep 3
            fi
            silentkill "$wsmpid"
            ;;
        "${actions[1]}")
            sudo pm-hibernate
            ;;
        "${actions[2]}")
            sudo pm-suspend
            ;;
        "${actions[3]}")
            sudo reboot
            ;;
        "${actions[4]}")
            sudo shutdown now -h
            ;;
        "${actions[5]}")
            [[ -f "$wmfile" ]] &&
                cp "$wmfile" "$savefile"
            ;;
        *)
            if ! which "$selection" &> /dev/null; then
                osd -c red -t2 'No such binary.'
                exit 1
            fi
            echo "$selection" > "$wmfile"
            [[ "$wm" ]] &&
                silentkill {"$wm","${wm%-session*}"}{,-$HOSTNAME}
            ;;
    esac
    exit
fi


echo $$ > "$pidfile"
echo "${wms[0]}" > "$wmfile"
chmod 644 "$pidfile" "$wmfile"

feh --bg-fill ~/.background-busy
[[ -f ~/.xautostart ]] && bash ~/.xautostart &
[[ -f "$savefile" ]] && cp "$savefile" "$wmfile"

while :; do
    [[ -f "$wmfile" ]] && wm=$(cat "$wmfile") || break
    which "$wm" &> /dev/null || wm=${wms[0]}
    if ! which "$wm" &> /dev/null; then
        osd -c red -t4 "Window manager $wm is not installed."
        break
    fi


    xrefresh
    osd -c yellow -t2 -v top "Starting $wm..." &
    setxkbmap -layout 'us(colemak),us' -option 'compose:ralt' \
        -option 'grp:shift_caps_toggle' -option 'keypad:pointerkeys'
    xbindkeys
    syndaemon -d -t -i2
    dunst $DMENU_OPTIONS &
    case "$wm" in
        'musca')
            musca -s ~/.config/musca/start &> /dev/null
            ;;
        'i3')
            i3 --version | grep -q tree &&
                i3 -c ~/.config/i3/config.tree ||
                i3 -c ~/.config/i3/config
            ;;
        *)
            "$wm"
            ;;
    esac
    feh --bg-fill ~/.background-busy
    xsetroot -solid black
    xrefresh
    silentkill -w ${reset[@]} 2&> /dev/null
done
