#!/bin/bash
### MPlayer: Audio via Loopback #######
# Version 20120711-1 by Scott Garrett #
# Wintervenom [(at)] archlinux.us     #
#######################################
# Try to connect in the background because we want MPlayer to still be
# controllable from the terminal.
jack-connect2 -R -w5 'mplayer-loopback:' 'loopback_in:playback' loop_c_active &
mplayer -ao jack:name=mplayer-loopback "$@"
kill $(jobs -p) 2>/dev/null
wait
jack-connect2 -d 'mplayer-loopback:' 'loopback_in:playback'
