#!/bin/bash
### FFMPEG Android Converter ###
# Version 0.1 by Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################
# Directory to save converted videos to.
d='mobile'

# Clean up on exit.
cleanup () {
    rm "$d"/*.tmp.*
    exit
}

# Convert to Android-friendly format; scale to fit screen and preserve the
# aspect ratio and add hint tracks to make the video streamable.
convert () {
    nf="$d/${1%.*}"
    ffmpeg -y -i "$1" -nodump -acodec libfaac -ac 2 -ab 128k -vcodec libx264 \
        -vf "scale=trunc(oh*a/2)*2:240,unsharp" -vpre slow -vpre ipod640 \
        -f mp4 "$nf.tmp.mp4"
    [[ $? != 0 ]] &&
        echo "$f" >> "failed.${0##*/}.log"
    if [[ -f "$nf.tmp.mp4" ]]; then
        qt-faststart "$nf.tmp.mp4" "$nf.mp4"
        rm -f "$nf.tmp.mp4"
    fi
}

trap cleanup INT TERM
mkdir -p "$d"
for f in "$@"; do
    if [[ ${f#*.} != 'txt' ]]; then
        convert "$f"
    else
        while read f; do
            convert "$f"
        done < "$f"
    fi
done
