#!/usr/bin/env python2
import sys
import os
import fnmatch
import subprocess


if len(sys.argv) < 2:
    sys.exit('Missing arguments. Syntax: FILE [FILE ...]')

archive_handlers = [
    ['tar.bz2', ['tar', '-xjf']],
    ['tar.gz', ['tar', '-xzf']],
    ['tar.lzma', ['tar', '--lzma', '-xf']],
    ['tar.xz', ['tar', '--xz', '-xf']],
    ['tar', ['tar', '-xf']],
    ['7z', ['7z', 'x']],
    ['bz2', ['bunzip2', '--best']],
    ['gz', ['gunzip', '--best']],
    ['rar', ['unrar', 'x', '-ad']],
    ['tbz2', ['tar', '-xjf']],
    ['tgz', ['tar', '-xzf']],
    ['tlzma', ['tar', '--lzma', '-xf']],
    ['txz', ['tar', '--xz', '-xf']],
    ['z', ['uncompress', '--best']],
    ['zip', ['unzip']]
]

for filename in sys.argv[1:]:
    match = False
    for filetype, handler in archive_handlers:
        if fnmatch.fnmatch(filename, '*.' + filetype):
            match = True
            subprocess.call(handler + [filename])
            break
    if not match:
        print('Archive type not recognized.')

