#!/bin/bash
### Resume Screen ##############
# Version 0.1 by Scott Garrett #
# Wintervenom ([at]) gmail.com #
################################

###############
### Globals ###
###############

sessions=($(screen -list | grep '(Detached)' | awk '{print $1}'))



############
### Main ###
############

[[ ${#sessions[@]} = 0 ]] && exit
if [[ ${#sessions[@]} < 2 && "$1" != '-i' ]]; then
    screen -D -RR
else
    while :; do
        echo -e "Resume which Screen session?\n"
        x=1
        for session in ${sessions[@]}; do
            echo -e "$((x++))\t${session}"
        done
        echo -e "0\tContinue to shell"
        #echo -e "-\t"
        read -p '>' x
        clear
        [[ "$x" = 0 ]] && exit
        [[ "${sessions[((--x))]}" ]] && break
        echo 'No such session.'
    done
    exec screen -r ${sessions[((x))]}
fi
