#!/bin/bash
### Remote URL Handler #########
# Version 0.4 by Scott Garrett #
################################
shopt -s nocasematch
shopt -s extglob
DISPLAY=:0.0
BROWSER='firefox'
PATH="$HOME/bin:$PATH"
url=$*
file=$(basename "$url")
c='curl --connect-timeout 10'
[[ ${#file} -gt 40 ]] && s="${file:0:40}..." || s=$file
case "$url" in
    *@(youtu.be/|youtube.com/@(watch|v))*)
        o=ytdl-mplayer;;
    *)
        notify-send -t 5000 "Identifying remote file: \"$s\""
        t=$($c -I "$url" | awk -F'(:|;) ' '/^Content-Type/{print $2}')
        case "$t" in
            #'image/'*) o='mirage';;
            *'/'@(ogg|octet-stream)|@(audio|video)'/'*)
                o='urxvt -e mplayer';;
            *'/vnd.oasis.'*)
                o=libreoffice;;
            *'/p'@(ostscript|df))
                o=evince;;
            *'/'@(text|css))
                o=gvim;;
            *'/zip')
                f=$($c -I "$url" | grep -o 'filename=.*' | sed 's/filename="\(.*\)"/\1/')
                [[ -z "$f" ]] && f="$file"
                f=${f##*.}
                case "$f" in
                    @(doc|ppt|xls)x*)
                        o=libreoffice;;
                esac
                ;;
            *)
                o=$BROWSER;;
        esac
        ;;
esac
shopt -u nocasematch
notify-send -t 5000 "Opening \"$s\" with ${o%% *}"
$o "$url" & disown
