#!/bin/bash
declare -A options=(
    ['global']='-dalsa -dhw:0 -r44100 -S -Xseq'
    ['iandrio']='-n3 -p512'
    ['succubine']='-n2 -p256'
)

kill_jack () {
    killall "$@" jackd 2>/dev/null
}

cleanup () {
    event-scripts jack pre-stop
    kill_jack
    sleep 1
    if kill_jack -0; then
        sleep 4
        kill_jack -9
    fi
    wait
    event-scripts jack post-stop
    exit
}

trap cleanup INT TERM HUP
event-scripts jack pre-start
jackd ${options['global']} ${options["$HOSTNAME"]} &
for ((n=0; n<5; n++)); do
    sleep 1
    if kill -0 $! 2>/dev/null; then
        event-scripts jack post-start
        break
    fi
done
wait
if ! kill_jack -0; then
    event-scripts jack pre-stop
    event-scripts jack post-stop
fi
