#!/bin/bash
### Superclean Incenerator #####
# Version 0.2 By Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################
# Arguments                    #
# -q  Be quiet.                #
# -r  Rush mode.               #
# -f  Wipe free space.         #
################################

###############
### Globals ###
###############

kill_processes=(firefox firefox-bin-beta firefox-bin chromium midori)
static_incinerate=(
    $HOME/.{recently-used,thumbnails}*
    $HOME/.mozilla/firefox/*/{Cache,cookies,downloads,formhistory,sessionstore}*
    $HOME/.vimperator/info/*/history-*
    $HOME/.bash_history
    $HOME/.secondlife/{cache,logs,*/{screen_last,url_history}*}
    #$HOME/{.purple,.weechat,.irssi}/{logs,Logs,icons}
    $HOME/.cache/{Thunar/thumbnailers.cache,chromium}
    $HOME/.config/chromium/*/{History,Cookies,Current,Thumbnails,Visited,Archived}*
    $HOME/.local/{share/,}{Trash,user-places*}
    /tmp/{ff-cache,*.torrent}
)
scan_incinerate=(
    '*~'
    '*.tmp'
    '*.temp'
    '.*.swp'
    '.*.tmp'
    '.unison.*'
    'thumbs.db'
    'desktop.ini'
    #'*_history*'
    '.directory'
    '$RECYCLE*'
)

pass_dir="$HOME/.pass"
incinerate_mode='D' #DoD seven-pass mode.




############
### Main ###
############
clear

if [ "$1" != '-q' ]; then verbose=1; else shift; fi
if [ "$1" != '-f' ]; then norush=1; else incinerate_mode='s'; shift; fi
if [ "$1"  = '-s' ]; then wipefree=1; else shift; fi

for process in ${kill_processes[@]}; do
    if pidof $process &>/dev/null; then
        [ $verbose ] && echo "Sending terminate signal to process '$process'..."
        killall $process
    fi
done

[ $norush ] && {
[ $verbose ] && echo "Giving processes time to act..."
sleep 5
}

for process in ${kill_processes[@]}; do
    if pidof $process &>/dev/null; then
        [ $verbose ] && echo "'$process' is still running -- forcing it to die."
        killall -9 $process
    fi
done

[ $verbose ] && echo "Processes terminated.  Time to destroy shit."

for target in ${static_incinerate[@]}; do
    if [ -e "$target" ]; then
        [ $verbose ] && echo "Incinerating '$target'..."
        srm -${incinerate_mode}rf "$target"
    fi
done

for target in ${scan_incinerate[@]}; do
    [ $verbose ] && echo "Scanning for and incinerating '$target'..."
    find "$HOME" -iname "$target" -print -exec srm -${incinerate_mode}rf {} \;
done

[ $verbose ] && echo "Vacuuming Firefox SQLite databases..."
for f in $HOME/.mozilla/firefox/*/*.sqlite; do sqlite3 $f 'VACUUM;'; done

if [ $wipefree ]; then
    [ $verbose ] && echo "Wiping free space (this may take a long-ass time)..."
    mkdir -p "$pass_dir"
    while dd if=/dev/zero of="$pass_dir/$RANDOM$RANDOM$RANDOM$RANDOM" bs=1M count=256; do
        true
    done
    sync
    rm -rf "$pass_dir"
fi

[ $verbose ] && echo "Cleaning complete."


