#!/bin/bash
### Remote URI Handler #########
# Version 0.3 by Scott Garrett #
################################
shopt -s nocasematch
shopt -s extglob
DISPLAY=:0.0
BROWSER='firefox'
PATH="$HOME/bin:$PATH"
uri=$*
file=$(basename "$uri")
wget="wget -c -t3 -T15"
[[ ${#file} -gt 20 ]] && s="${file:0:20}..." || s=$file
case "$(osd -bt0 -c yellow "Identifying remote file\n'$s'" | curl -I --connect-timeout 15 "$uri" | awk -F'(:|;) ' '/^Content-Type/{print $2}')" in
    #'image/'*) o='mirage';;
    *'/'@(ogg|octet-stream)|@(audio|video)'/'*) o='urxvt -e mplayer';;
    *'/vnd.oasis.'*) o=libreoffice;;
    *'/p'@(ostscript|df)) o=evince;;
    *'/'@(text|css)) o=gvim;;
    *'/zip')
        f=$(osd -bt0 -c yellow "Identifying remote file\n'$s'" | curl -I --connect-timeout 15 "$uri" | grep -o 'filename=.*' | sed 's/filename="\(.*\)"/\1/')
        [[ -z "$f" ]] && f="$file"
        f=${f##*.}
        case "$f" in
            @(doc|ppt|xls)x*) o=libreoffice;;
            *)
                osd -bt0 -c yellow "Downloading remote file\n$s" | $wget -O "/tmp/$file" "$uri"
                uri="/tmp/$file"
                o=file-roller;;
        esac;;
    *) o=$BROWSER;;
esac
shopt -u nocasematch
(sleep 1; osd -t1 "Opened remote file\n'$s'\nwith ${o%% *}") &
$o "$uri" & detach
