#!/bin/bash
### MPD Relevant Track NP ######
# Version 0.1 by Scott Garrett #
# Wintervenom [(at)] gmail.com #
################################
# Dependencies:
#
# mpc
basename=${0##*/}
set -f
cache="$HOME/.cache/relevant-track.cache"
status="$USER"
if [[ "$cache" ]]; then
    IFS=$'\t'
    trigger=($(tail -10 "$cache" | grep -F "$(mpc current -f '%file%')" | cut -f2-))
    [[ "$trigger" ]] && status="${trigger[0]}: ‹${trigger[1]}›"
fi
file=$(mpc current -f '%file%')
if [[ "$file" ]]; then
    echo "Playing $(mpc current -f '"%title%"|%file%[ by %artist%]'), in response to $status"
else
    echo "Not playing anything."
fi

