#!/bin/bash
tmp="/tmp/channels.conf.new"
target="$HOME/.mplayer/channels.conf"
names="$HOME/.mplayer/suddenlink-channels"
blacklist="$HOME/.mplayer/suddenlink-blacklist"
if [[ -z "$1" ]]; then
    w_scan -fa -c US -A3 -M -R0 -O0 -E0 -t2 > "$tmp"
elif [[ ! -f "$1" ]]; then
    echo "No such file or invalid."
    exit 1
else
    cp "$1" "$tmp"
fi
if ! [[ -f "$names" ]]; then
    mkdir -p "${names%/*}"
    touch "$names"
fi
[[ ! -f "$blacklist" ]] && touch "$blacklist"
while read -r channel; do
    sed -r -i "s/[^:]+(.*:.*:${channel#*:})$/${channel%:*}\1/" "$tmp"
done < "$names"
sed -r -i 's/\[|\]//g' "$tmp"
sed -r -i 's/^ *(.*) *:/\1:/g' "$tmp"
grep -Evf "$blacklist" "$tmp" | sort -n -k6 -t':' > "$target"
rm "$tmp"
