#!/bin/bash
tmp="/tmp/channels.conf.new"
target="$HOME/.mplayer/channels.conf.new"
tuning="$HOME/.mplayer/suddenlink-transports"
names="$HOME/.mplayer/suddenlink-channels"
dups=0
if [[ -z "$1" ]]; then
    if ! [[ -e "$tuning" ]]; then
        mkdir -p "${tuning%/*}"
        w_scan -fa -A2 -c US -E0 -t2 -RO -E0 -x >> "$tuning"
    fi
    scan -t1 -A2 -x0 -t1 "$tuning" > "$tmp"
else
    if [[ ! -f "$1" ]]; then
        echo "No such file or invalid."
        exit 1
    fi
    cp "$1" "$tmp"
fi
if ! [[ -e "$names" ]]; then
    mkdir -p "${names%/*}"
    touch "$names"
fi
while read channel; do
    sed -r -i "s/[^:]+(.*:.*:${channel#*:})$/${channel%:*}\1/" "$tmp"
done < "$names"
sed -r -i 's/\[|\]//g' "$tmp"
sed -r -i 's/^ *(.*) *:/\1:/g' "$tmp"
sort -n -k6 -t':' "$tmp" > "$target"
