#!/bin/dash
d=dwm-$(hostname)
while :; do
  if ! which $d; then
    dwm-recompile || exit 1
  fi
  killall barstatus
  barstatus &
  feh --bg-fill ~/.background &
  $d 2> ~/tmp/.dwm.log
  osd -t1 -c yellow 'DWM restarted'
done

