#!/bin/bash
mem_avail=$(free -m | grep Mem: | cut -f2 -d: | awk '{ print $1 }')
mem_used=$(free -m | grep cache: | cut -f2 -d: | awk '{ print $1 }')
mem_free=$(free -m | grep cache: | cut -f2 -d: | awk '{ print $2 }')
mem_tmpfs=$(df -m /dev/shm/ | tail -n1 | awk '{print $3}')
if [[ "$mem_tmpfs" == 0 ]]; then
    mem_tmpfs='Nothing is'
else
    mem_tmpfs="${mem_tmpfs}M are allocated"
fi

echo "There are ${mem_avail}M of RAM available.  Of that, ${mem_used}M are in use, leaving ${mem_free}M free.  ${mem_tmpfs} allocated to tmpfs."
