#!/usr/bin/env python3

import os
import sys

for d in sys.argv[1:]:
    if os.path.exists(d):
        for f in iter(os.listdir(d)):
            os.renames(os.path.join(d, f),
                       os.path.join(d, f.lower().rsplit('.', 2)[-1], f))
