#!/usr/bin/env python3

import os
import re
import sys

INVALIDS = re.compile(r'\.+$')

def clean(name):
    name = ' '.join(name.split())
    name = INVALIDS.sub('', name)
    return name.strip()

for d in sys.argv[1:]:
    if os.path.exists(d):
        for f in iter(os.listdir(d)):
            name = f.split(' - ', 1)
            if len(name) != 0:
                try:
                    os.renames(os.path.join(d, f),
                               os.path.join(d, clean(name[0]), clean(f)))
                except OSError:
                    pass
            else:
                try:
                    os.renames(os.path.join(d, f), os.path.join(d, clean(f)))
                except OSError:
                    pass

