#!/bin/bash
while [[ $1 ]]; do
    notify-send -t 2000 "Fetching info: $1"
    title=$(youtube-dl -e "$1")
    if [[ -z $title ]]; then
        notify-send -t 5000 "Can't find video at URL: $1"
        exit 1
    fi
    notify-send -t 5000 "Playing video: $title"
    url=$(youtube-dl --max-quality 22 -g "$1")
    shift
    mplayer -cache 1024 "$url"
done
