#!/bin/bash
basename=${0##*/}
plugins=(
http://weechat.org/files/scripts/beep.pl
http://weechat.org/files/scripts/buffer_autoclose.py
http://weechat.org/files/scripts/grep.py
http://weechat.org/files/scripts/highmon.pl
http://weechat.org/files/scripts/nickregain.pl
http://weechat.org/files/scripts/screen_away.py
http://weechat.org/files/scripts/shell.py
http://weechat.org/files/scripts/urlgrab.py
http://weechat.org/files/scripts/buffers.pl
http://weechat.org/files/scripts/buffer_swap.py
http://weechat.org/files/scripts/go.py
http://weechat.org/files/scripts/iset.pl
)

for plugin in ${plugins[@]}; do
    case "${plugin##*.}" in
        'py')
            plang='python' ;;
        'pl')
            plang='perl'   ;;
        'lua')
            plang='lua'    ;;
    esac
    if [[ ${plang} ]]; then
        wget -t3 -T10 -w5 -O "${HOME}/.weechat/${plang}/autoload/${plugin##*/}" "${plugin}"
    else
        echo "${basename}: Plugin '${plugin}' is not supported."
    fi
    shift
done

