#!/bin/bash
library="${HOME}/Documents/Software"
docs=(
    'Shell/Bash/Advanced Bash Scripting Guide.pdf|http://www.tldp.org/LDP/abs/abs-guide.pdf'
    'Haskell/[Various Authors] - Haskell.pdf|http://upload.wikimedia.org/wikipedia/commons/2/26/Haskell.pdf'
    'Window Managers/i3 User Guide.htm|http://i3.zekjur.net/docs/userguide.html'
    'Haskell/Miran Lipovaˇa - Learn You A Haskell for Great Good!.pdf|http://learnyouahaskell.com/learnyouahaskell.pdf'
    'Haskell/[Various Authors] - Learn Haskell in 10 Minutes.htm|http://www.haskell.org/haskellwiki/index.php?title=Learn_Haskell_in_10_minutes&printable=yes'
    'Shell/Bruce Barnett - Sed, An Introduction and Tutorial.htm|http://www.grymoire.com/Unix/Sed.html'
)

for doc in "${docs[@]}"; do
    IFS='|' doc=(${doc})
    echo "${doc[1]}"
    wget "${doc[1]}" -O "${library}/${doc[0]}"
done
