#!/bin/bash

# A bit of cleaning
rm -rf /tmp/hosts &>/dev/null
sed -i '/\#START HOSTS APPEND/,/#END HOSTS APPEND/d' /etc/hosts


# Download host files, and append
URLS=('http://www.mvps.org/winhelp2002/hosts.txt')
      

echo 'Downloading blacklists...'
for url in "${URLS[@]}"; do
    echo -n "  $url ..."
    wget -cq -T30 "$url" -O- >> /tmp/hosts &&
        echo ' okay.' ||
        echo ' FAILED.'
done

# Append indication of the begining of the section in the /etc/hosts file
echo "#START HOSTS APPEND" >> /etc/hosts

# Fix file and append
cat /tmp/hosts | grep -v "localhost" | sed 's/127.0.0.1\s*/0.0.0.0 /g; s/\x0D$//' | sort | uniq -u >> /etc/hosts

# Append indication of the ending of the section in the /etc/hosts file
echo "#END HOSTS APPEND" >> /etc/hosts


# Delete tmp files
rm /tmp/hosts

