#!/bin/bash
### Update Local Repos #############
# Ver. 20111121-1 by Scott Garrett #
# Wintervenom [(at)] archlinux.us  #
####################################
repos="$HOME/Projects"
r_cfg="Configs"
r_bin="Scripts"

configs=(
    /etc/X11/xorg.conf,$r_cfg/X11
    ~/.xbindkeysrc,$r_cfg/xbindkeys
    ~/.Xdefaults,$r_cfg/X11
    ~/.bashrc,$r_cfg/bash
    ~/.config/herbstluftwm/{autostart,layouts}
    ~/.config/i3/{config,layouts}
    ~/.config/i3status/config
    ~/.config/mpd/mpd.conf
    ~/.config/openbox/
    ~/.config/ranger/{{apps,options}.py,rc.conf}
    ~/.config/xmobar/
    ~/.config/zathura/zathurarc
    ~/.dwm/config.h,$r_cfg/dwm
    ~/.fonts.conf,$r_cfg/fontconfig
    ~/.pentadactylrc,$r_cfg/pentadactyl
    ~/.vimrc,$r_cfg/vim
    diadian:.config/newsbeuter/config
    diadian:.muttrc,$r_cfg/mutt
    diadian:.rtorrent.rc,$r_cfg/rtorrent
    iandrio:.mplayer/,$r_cfg/mplayer
)

scripts=(
    volume,$r_bin/audio/alsa

    dmpc,$r_bin/audio/mpd
    np,$r_bin/audio/mpd

    mpc-addto,$r_bin/audio/mpd/mpc-utils
    mpc-all,$r_bin/audio/mpd/mpc-utils
    mpc-common,$r_bin/audio/mpd/mpc-utils
    mpc-delfrom,$r_bin/audio/mpd/mpc-utils
    mpc-faddto,$r_bin/audio/mpd/mpc-utils
    mpc-load,$r_bin/audio/mpd/mpc-utils
    mpc-rate,$r_bin/audio/mpd/mpc-utils
    mpc-save,$r_bin/audio/mpd/mpc-utils
    mpc-search,$r_bin/audio/mpd/mpc-utils
    mpc-stats,$r_bin/audio/mpd/mpc-utils
    mpc-toggle-eq,$r_bin/audio/mpd/mpc-utils
    mpc-trash,$r_bin/audio/mpd/mpc-utils

    relevant-track,$r_bin/audio/mpd/relevant-track
    relevant-track-np,$r_bin/audio/mpd/relevant-track
    relevant-track-weechat,$r_bin/audio/mpd/relevant-track



    dl,$r_bin/network/downloaders
    vkdl,$r_bin/network/downloaders



    backup,$r_bin/file/backup
    backup-system,$r_bin/file/backup

    sample-dups,$r_bin/file/cleanup
    superclean,$r_bin/file/cleanup

    archive,$r_bin/file/helpers
    extract,$r_bin/file/helpers

    organize-by-creator,$r_bin/file/organizers
    organize-by-name,$r_bin/file/organizers
    organize-by-type,$r_bin/file/organizers



    dmenu-launch,$r_bin/launchers
    firefox-launch,$r_bin/launchers
    launch,$r_bin/launchers
    mupen-launch,$r_bin/launchers
    uri-open,$r_bin/launchers



    login-action-menu,$r_bin/login
    resume-screen,$r_bin/login
    wm-session-manager,$r_bin/login
    xlogin,$r_bin/login



    battery-monitor,$r_bin/status
    osd,$r_bin/status

    barstatus,$r_bin/status/barstatus
    barstatus-dzen2,$r_bin/status/barstatus
    barstatus-i3bar,$r_bin/status/barstatus
    barstatus-xmobar,$r_bin/status/barstatus

    human-diskinfo,$r_bin/status/human-sysinfo
    human-mpdinfo,$r_bin/status/human-sysinfo
    human-videoinfo,$r_bin/status/human-sysinfo

    xmobar-np-mpd,$r_bin/status/xmobar
    xmobar-wireless-info,$r_bin/status/xmobar



    rc,$r_bin/utils/system

    tohex,$r_bin/utils/text
    urldecode,$r_bin/utils/text
    urlencode,$r_bin/utils/text



    lottery,$r_bin/toys
    lucid,$r_bin/toys
    random-word,$r_bin/toys
    self-pong,$r_bin/toys
    tclock,$r_bin/toys

    arch-splash,$r_bin/toys/arch
    archlogo,$r_bin/toys/arch

    schizo,$r_bin/toys/dangerous



    bg-scheme,$r_bin/terminal/colorscheme-generator
    term-color-generator,$r_bin/terminal/colorscheme-generator

    colorblocks,$r_bin/terminal/tests
    colorcodes,$r_bin/terminal/tests
    colorwall,$r_bin/terminal/tests

    fbterm-tint,$r_bin/terminal/wrappers



    update-ipfilters,$r_bin/updaters
    update-repos,$r_bin/updaters
    update-mvps,$r_bin/updaters
    update-pentadactyl-plugins,$r_bin/updaters
    update-weechat-plugins,$r_bin/updaters



    tv,$r_bin/video/tv
    tv-scan,$r_bin/video/tv



    dwm-recompile,$r_bin/wm/dwm
    dwm-session,$r_bin/wm/dwm
    dwm-update,$r_bin/wm/dwm

    hlwm-layout-manager,$r_bin/wm/herbstluftwm
    hlwm-xmobar,$r_bin/wm/herbstluftwm
    hlwm-xmobar-tags,$r_bin/wm/herbstluftwm

    musca-fullscreen,$r_bin/wm/musca
)


declare -A redact
redact["$repos/$r_cfg/mpd/mpd.conf"]='(password +").*(")'
redact["$repos/$r_cfg/newsbeuter/config"]='((login|password) +").*(")'
redact["$repos/$r_cfg/mutt/.muttrc"]='((_pass|_url|_user|realname).+").*(")'


sync () {
    t="$repos/${2:-$r_bin/${1##*/}}"
    mkdir -p "$t"
    rsync -aP "$1" "$t"
}

sanitize () {
    for file in "${!redact[@]}"; do
        sed -ri 's#'"${redact[$file]}"'#\1[redacted]\2#' $file
    done
}

update_configs () {
    local p t
    for p in "${configs[@]}"; do
        t=${p#*:}
        t=${t#$HOME/}
        t=${t%/*}
        t=${t##*/}
        t=${t#*.}
        sync $p "$r_cfg/$t"
    done
}

update_scripts () {
    local s
    for s in "${scripts[@]}"; do
        sync $HOME/bin/$s
    done
}


IFS=','
mkdir -p "$repos"/{"$r_cfg","$r_bin"}
rm -r "$repos/$r_cfg/"*
rm -r "$repos/$r_bin/"*
update_configs
update_scripts
sanitize
